# Generated by Django 3.2.7 on 2021-09-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='Sub_Category',
        ),
    ]
