# Generated by Django 3.2.7 on 2021-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0006_alter_course_about_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos'),
        ),
    ]
